#import "AppTroveExpoSdk.h"
#import <React/RCTLog.h>
#import <React/RCTUtils.h>

// Import the Swift bridge header generated by Xcode
// The header name is based on the module name (pod name with dashes replaced)
#if __has_include("apptrove_expo_sdk-Swift.h")
#import "apptrove_expo_sdk-Swift.h"
#elif __has_include("apptrove-expo-sdk-Swift.h")
#import "apptrove-expo-sdk-Swift.h"
#elif __has_include(<apptrove_expo_sdk/apptrove_expo_sdk-Swift.h>)
#import <apptrove_expo_sdk/apptrove_expo_sdk-Swift.h>
#endif

@implementation AppTroveExpoSdk

RCT_EXPORT_MODULE(AppTroveExpoSdk);

- (NSArray<NSString *> *)supportedEvents {
  return @[@"apptrove_deferredDeeplink"];
}

RCT_EXPORT_METHOD(initializeSDK:(NSDictionary *)config) {
  // Set up notification observer for deep link events before initializing
  if (config[@"hasDeferredDeeplinkCallback"] && [config[@"hasDeferredDeeplinkCallback"] boolValue]) {
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(handleDeepLinkNotification:)
                                                 name:@"AppTroveDeepLinkReceived"
                                               object:nil];
  }
  
  [AppTroveSDKBridge initializeSDKWithConfig:config];
}

- (void)handleDeepLinkNotification:(NSNotification *)notification {
  NSString *url = notification.userInfo[@"url"];
  if (url) {
    [self sendEventWithName:@"apptrove_deferredDeeplink" body:url];
  }
}

- (void)dealloc {
  [[NSNotificationCenter defaultCenter] removeObserver:self];
}

RCT_EXPORT_METHOD(setEnabled:(BOOL)value) {
  [AppTroveSDKBridge setEnabled:value];
}

RCT_EXPORT_METHOD(getAppTroveId:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject) {
  NSString *appTroveId = [AppTroveSDKBridge getAppTroveId];
  resolve(appTroveId ?: @"");
}

RCT_EXPORT_METHOD(setUserId:(NSString *)userId) {
  [AppTroveSDKBridge setUserId:userId];
}

RCT_EXPORT_METHOD(setUserEmail:(NSString *)userEmail) {
  [AppTroveSDKBridge setUserEmail:userEmail];
}

RCT_EXPORT_METHOD(setUserName:(NSString *)userName) {
  [AppTroveSDKBridge setUserName:userName];
}

RCT_EXPORT_METHOD(setUserPhone:(NSString *)userPhone) {
  [AppTroveSDKBridge setUserPhone:userPhone];
}

RCT_EXPORT_METHOD(trackAsOrganic:(BOOL)value) {
  [AppTroveSDKBridge trackAsOrganic:value];
}

RCT_EXPORT_METHOD(setLocalRefTrack:(NSString *)value delimiter:(NSString *)delimiter) {
  // Note: Swift SDK might not have this exact method
}

RCT_EXPORT_METHOD(setUserAdditionalDetails:(NSDictionary *)userAdditionalMap) {
  [AppTroveSDKBridge setUserAdditionalDetails:userAdditionalMap];
}

RCT_EXPORT_METHOD(waitForATTUserAuthorization:(NSInteger)timeoutInterval) {
  [AppTroveSDKBridge waitForATTUserAuthorization:(int)timeoutInterval];
}

RCT_EXPORT_METHOD(updateAppleAdsToken:(NSString *)token) {
  [AppTroveSDKBridge updateAppleAdsToken:token];
}

RCT_EXPORT_METHOD(updatePostbackConversion:(NSInteger)conversionValue) {
  [AppTroveSDKBridge updatePostbackConversion:(int)conversionValue];
}

RCT_EXPORT_METHOD(subscribeDeeplink) {
  [AppTroveSDKBridge subscribeDeeplink];
}

RCT_EXPORT_METHOD(fireInstall) {
  // Note: Swift SDK might not have fireInstall
}

RCT_EXPORT_METHOD(parseDeepLink:(NSString *)value) {
  [AppTroveSDKBridge parseDeepLink:value];
}

RCT_EXPORT_METHOD(setIMEI:(NSString *)imei1 imei2:(NSString *)imei2) {
  // Note: Swift SDK might not have setIMEI
}

RCT_EXPORT_METHOD(setMacAddress:(NSString *)macAddress) {
  // Note: Swift SDK might not have setMacAddress
}

RCT_EXPORT_METHOD(getAd:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject) {
  NSString *ad = [AppTroveSDKBridge getAd];
  resolve(ad ?: @"");
}

RCT_EXPORT_METHOD(getAdID:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject) {
  NSString *adID = [AppTroveSDKBridge getAdID];
  resolve(adID ?: @"");
}

RCT_EXPORT_METHOD(getAdSet:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject) {
  NSString *adSet = [AppTroveSDKBridge getAdSet];
  resolve(adSet ?: @"");
}

RCT_EXPORT_METHOD(getCampaign:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject) {
  NSString *campaign = [AppTroveSDKBridge getCampaign];
  resolve(campaign ?: @"");
}

RCT_EXPORT_METHOD(getCampaignID:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject) {
  NSString *campaignID = [AppTroveSDKBridge getCampaignID];
  resolve(campaignID ?: @"");
}

RCT_EXPORT_METHOD(getChannel:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject) {
  NSString *channel = [AppTroveSDKBridge getChannel];
  resolve(channel ?: @"");
}

RCT_EXPORT_METHOD(getP1:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject) {
  NSString *p1 = [AppTroveSDKBridge getP1];
  resolve(p1 ?: @"");
}

RCT_EXPORT_METHOD(getP2:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject) {
  NSString *p2 = [AppTroveSDKBridge getP2];
  resolve(p2 ?: @"");
}

RCT_EXPORT_METHOD(getP3:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject) {
  NSString *p3 = [AppTroveSDKBridge getP3];
  resolve(p3 ?: @"");
}

RCT_EXPORT_METHOD(getP4:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject) {
  NSString *p4 = [AppTroveSDKBridge getP4];
  resolve(p4 ?: @"");
}

RCT_EXPORT_METHOD(getP5:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject) {
  NSString *p5 = [AppTroveSDKBridge getP5];
  resolve(p5 ?: @"");
}

RCT_EXPORT_METHOD(getClickId:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject) {
  NSString *clickId = [AppTroveSDKBridge getClickId];
  resolve(clickId ?: @"");
}

RCT_EXPORT_METHOD(getDlv:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject) {
  NSString *dlv = [AppTroveSDKBridge getDlv];
  resolve(dlv ?: @"");
}

RCT_EXPORT_METHOD(getPid:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject) {
  NSString *pid = [AppTroveSDKBridge getPid];
  resolve(pid ?: @"");
}

RCT_EXPORT_METHOD(getIsRetargeting:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject) {
  BOOL retargeting = [AppTroveSDKBridge getIsRetargeting];
  resolve(@(retargeting));
}

RCT_EXPORT_METHOD(trackEvent:(NSDictionary *)eventMap) {
  [AppTroveSDKBridge trackEvent:eventMap];
}

RCT_EXPORT_METHOD(createDynamicLink:(NSDictionary *)config resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject) {
  NSMutableDictionary *mutableConfig = [config mutableCopy];
  
  [AppTroveSDKBridge createDynamicLinkWithConfig:mutableConfig onSuccess:^(NSString *dynamicLinkUrl) {
    resolve(dynamicLinkUrl);
  } onFailure:^(NSString *error) {
    reject(@"CREATE_DYNAMIC_LINK_FAILED", error, nil);
  }];
}

RCT_EXPORT_METHOD(resolveDeeplinkUrl:(NSString *)url resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject) {
  [AppTroveSDKBridge resolveDeeplinkUrlWithUrl:url onSuccess:^(NSDictionary *result) {
    resolve(result);
  } onFailure:^(NSString *error) {
    reject(@"RESOLVE_DEEPLINK_FAILED", error, nil);
  }];
}

+ (BOOL)requiresMainQueueSetup {
  return NO;
}

@end
